version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "8000:8000"
    depends_on:
      - "db"
  
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    ports:
      - "3306:3006"
    
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: