version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: User_service
    ports:
      - "8001:8000"
    depends_on:
      - "db"
  
  db:
    image: postgres
    container_name: User_postgres_database
    ports:
      - '5433'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase

volumes:
  postgres_data: